baseurl                  = "/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Định Nguyễn"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "dinhnn.com by Định Nguyễn Ngọc."

# Metadata for Open Graph and Twitter
    description          = "Chém gió, viết nhảm!"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Định Nguyễn"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "videos/ocean.mp4"
    type    = "video/mp4"
    poster  = "images/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "about"
    text = "who is Định?"

[imaging]
    quality = 75
